import type { BuildingDefinition, BuildingType } from '../building/types';
import type { EraId } from '../progression/era';

/**
 * Gameplay balance numbers, tuned for a calm game: the city never fails, shortages slow it
 * down gently instead of stopping it, and costs grow slowly enough that progress keeps
 * feeling steady.
 */

export const ECONOMY = {
  startingGold: 80,
  /** Gold per second the Town Hall collects for each whole citizen. */
  taxPerCitizenPerSecond: 0.12,
  /** Citizens gained per second while population is below housing capacity (at neutral mood). */
  populationGrowthPerSecond: 0.5,
} as const;

/** Per-era difficulty and reward scaling (design brief §35). */
export const ERA_SETTINGS: Record<
  EraId,
  { costMultiplier: number; outputMultiplier: number; powerDemandMultiplier: number }
> = {
  ancient: { costMultiplier: 1, outputMultiplier: 1, powerDemandMultiplier: 1 },
  medieval: { costMultiplier: 1.4, outputMultiplier: 1.8, powerDemandMultiplier: 1.35 },
  industrial: { costMultiplier: 1.9, outputMultiplier: 3, powerDemandMultiplier: 1.9 },
  modern: { costMultiplier: 2.4, outputMultiplier: 4.5, powerDemandMultiplier: 2.3 },
};

/**
 * What a city needs to enter each later era (design brief §10): population and city level
 * here, plus the research whose `opensEra` names the era.
 */
export const ERA_REQUIREMENTS: Record<Exclude<EraId, 'ancient'>, { population: number; cityLevel: number }> = {
  medieval: { population: 40, cityLevel: 4 },
  industrial: { population: 120, cityLevel: 7 },
  modern: { population: 250, cityLevel: 10 },
};

export const POWER = {
  /** Output share a power-hungry building keeps with no power at all. */
  minEfficiency: 0.7,
} as const;

export const STAFFING = {
  /** Output share a workplace keeps with nobody to staff it. */
  minEfficiency: 0.6,
} as const;

/** Neighbour effects between buildings (8 surrounding tiles). */
export const ADJACENCY = {
  radius: 1,
  shopPerHouseBonus: 0.15,
  shopMaxHouses: 3,
  factoryNearPowerBonus: 0.15,
  /** Trade and industry next to a road earn more. */
  roadGoldBonus: 0.12,
  /** Growth bonus scales with the share of houses that have a park next door. */
  parkHomeGrowthBonus: 0.2,
  parkHomeHappiness: 5,
} as const;

export const POLLUTION = {
  /** Homes within this many tiles of a factory are affected. */
  radius: 2,
  happinessPerUnit: 7,
  maxPenalty: 14,
} as const;

export const PROBLEMS = {
  /** Below this city happiness, the city keeps growing but slowly (see HAPPINESS). */
  lowHappinessBelow: 40,
} as const;

export const HAPPINESS = {
  /** Mood of a housed, employed citizen in a city with no happiness buildings. */
  base: 50,
  unemployedPenalty: 12,
  /** Temporary bonus after a leisure visit, fading at leisureBoostDecayPerSecond. */
  leisureBoost: 10,
  leisureBoostDecayPerSecond: 0.2,
  /** Cap on the summed city-wide bonus from buildings such as parks. */
  maxBuildingBonus: 30,
  /** How fast a citizen's mood moves towards its target, in points per second. */
  adjustPerSecond: 5,
  unhappyBelow: 35,
  happyFrom: 70,
  /** Walk speed multiplier at 0 and at 100 happiness. */
  speedMultiplier: [0.6, 1.4],
  /** Population growth multiplier = happiness / base, clamped. */
  growthMultiplier: [0.85, 1.4],
  /** Growth never stops: unhappy cities keep this share of their growth. */
  unhappyGrowthMultiplier: 0.4,
} as const;

export const CITIZENS = {
  /** Simulated citizen entities; population beyond this is represented proportionally. */
  maxSimulated: 50,
  walkSpeedTilesPerSecond: 1.5,
  homeRestSeconds: [4, 10],
  workSeconds: [8, 16],
  leisureSeconds: [5, 10],
  /** Chance that free time (after work, or while unemployed) is spent at a leisure spot. */
  leisureChance: 0.6,
  /** Max distance from a leisure tile's centre where visitors stand, in tiles. */
  leisureSpreadTiles: 0.3,
} as const;

/** City XP and levels. */
export const PROGRESSION = {
  /** XP for level 1 -> 2; each later level needs xpGrowth times more. */
  baseXp: 35,
  xpGrowth: 1.4,
  maxLevel: 12,
  xp: {
    build: 10,
    /** Times the level reached. */
    upgradePerLevel: 8,
    expand: 40,
    research: 30,
    era: 100,
    /** For each new highest whole population. */
    citizen: 1,
  },
} as const;

export const LEVELING = {
  /** Each upgrade costs this many times the previous one. */
  upgradeCostGrowth: 1.55,
  /** Output bonus per level above 1 (0.5 means Lv2 = 150%, Lv3 = 200%). */
  outputBonusPerLevel: 0.5,
} as const;

const NO_OUTPUT = {
  goldPerSecond: 0,
  populationCapacity: 0,
  jobs: 0,
  happinessBonus: 0,
  leisureSpot: false,
  powerSupply: 0,
  powerDemand: 0,
  pollution: 0,
  research: 0,
} as const;

export const BUILDINGS: Record<BuildingType, BuildingDefinition> = {
  townHall: {
    ...NO_OUTPUT,
    category: 'civic',
    buildable: false,
    movable: false,
    era: 'ancient',
    cityLevel: 1,
    buildCost: 0,
    upgradeBaseCost: 0,
    maxLevel: 1,
    // Enough for the first few shops before a power plant is needed.
    powerSupply: 3,
  },
  house: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 1,
    buildCost: 10,
    upgradeBaseCost: 20,
    maxLevel: 5,
    populationCapacity: 5,
  },
  farm: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 1,
    buildCost: 18,
    upgradeBaseCost: 30,
    maxLevel: 4,
    goldPerSecond: 0.2,
    populationCapacity: 3,
    jobs: 2,
  },
  shop: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 1,
    buildCost: 25,
    upgradeBaseCost: 40,
    maxLevel: 5,
    goldPerSecond: 1,
    jobs: 4,
    powerDemand: 1,
  },
  workshop: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 45,
    upgradeBaseCost: 60,
    maxLevel: 4,
    goldPerSecond: 0.9,
    jobs: 3,
    powerDemand: 1,
  },
  park: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 30,
    upgradeBaseCost: 50,
    maxLevel: 3,
    happinessBonus: 6,
    leisureSpot: true,
  },
  well: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 40,
    upgradeBaseCost: 55,
    maxLevel: 3,
    jobs: 1,
    happinessBonus: 4,
  },
  inn: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 5,
    buildCost: 90,
    upgradeBaseCost: 120,
    maxLevel: 4,
    goldPerSecond: 1.2,
    jobs: 3,
    happinessBonus: 3,
    leisureSpot: true,
    powerDemand: 1,
  },
  powerPlant: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 60,
    upgradeBaseCost: 80,
    maxLevel: 5,
    jobs: 2,
    powerSupply: 8,
  },
  researchCenter: {
    ...NO_OUTPUT,
    category: 'science',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 4,
    buildCost: 120,
    upgradeBaseCost: 150,
    maxLevel: 5,
    jobs: 3,
    powerDemand: 2,
    research: 1,
  },
  monument: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 6,
    buildCost: 220,
    upgradeBaseCost: 300,
    maxLevel: 3,
    happinessBonus: 8,
  },
  granary: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 30,
    upgradeBaseCost: 40,
    maxLevel: 3,
    populationCapacity: 4,
    goldPerSecond: 0.1,
  },
  fishingHut: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 28,
    upgradeBaseCost: 36,
    maxLevel: 3,
    goldPerSecond: 0.6,
    jobs: 2,
  },
  hunterLodge: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 40,
    upgradeBaseCost: 50,
    maxLevel: 3,
    goldPerSecond: 0.8,
    jobs: 2,
  },
  orchard: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 45,
    upgradeBaseCost: 55,
    maxLevel: 3,
    goldPerSecond: 0.5,
    populationCapacity: 2,
  },
  potteryKiln: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 35,
    upgradeBaseCost: 45,
    maxLevel: 3,
    goldPerSecond: 0.7,
    jobs: 2,
  },
  weaversHouse: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 42,
    upgradeBaseCost: 52,
    maxLevel: 3,
    goldPerSecond: 0.8,
    jobs: 2,
  },
  quarry: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 4,
    buildCost: 60,
    upgradeBaseCost: 70,
    maxLevel: 3,
    goldPerSecond: 1.2,
    jobs: 3,
  },
  tradingPost: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 55,
    upgradeBaseCost: 65,
    maxLevel: 3,
    goldPerSecond: 1.1,
    jobs: 2,
  },
  campfire: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 1,
    buildCost: 12,
    upgradeBaseCost: 0,
    maxLevel: 1,
    happinessBonus: 2,
    leisureSpot: true,
  },
  storyGround: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 2,
    buildCost: 40,
    upgradeBaseCost: 50,
    maxLevel: 2,
    happinessBonus: 4,
    leisureSpot: true,
  },
  herbalist: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 3,
    buildCost: 45,
    upgradeBaseCost: 55,
    maxLevel: 3,
    happinessBonus: 3,
    jobs: 1,
  },
  watchtower: {
    ...NO_OUTPUT,
    category: 'civic',
    buildable: true,
    movable: true,
    era: 'ancient',
    cityLevel: 4,
    buildCost: 70,
    upgradeBaseCost: 80,
    maxLevel: 3,
    happinessBonus: 3,
  },
  bakery: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 4,
    buildCost: 90,
    upgradeBaseCost: 100,
    maxLevel: 4,
    goldPerSecond: 1.4,
    jobs: 3,
    happinessBonus: 1,
  },
  brewery: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 120,
    upgradeBaseCost: 140,
    maxLevel: 4,
    goldPerSecond: 1.8,
    jobs: 3,
  },
  marketSquare: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 4,
    buildCost: 100,
    upgradeBaseCost: 120,
    maxLevel: 2,
    goldPerSecond: 1.0,
    happinessBonus: 3,
    leisureSpot: true,
  },
  guildHall: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 6,
    buildCost: 200,
    upgradeBaseCost: 240,
    maxLevel: 4,
    goldPerSecond: 2.2,
    jobs: 4,
  },
  flourMill: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 4,
    buildCost: 95,
    upgradeBaseCost: 110,
    maxLevel: 4,
    goldPerSecond: 1.5,
    jobs: 3,
  },
  warehouse: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 110,
    upgradeBaseCost: 130,
    maxLevel: 4,
    goldPerSecond: 1.0,
    jobs: 2,
  },
  stonemason: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 130,
    upgradeBaseCost: 150,
    maxLevel: 4,
    goldPerSecond: 1.6,
    jobs: 3,
  },
  stable: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 4,
    buildCost: 85,
    upgradeBaseCost: 95,
    maxLevel: 3,
    happinessBonus: 2,
    jobs: 2,
  },
  bathhouse: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 140,
    upgradeBaseCost: 160,
    maxLevel: 3,
    happinessBonus: 6,
    leisureSpot: true,
    jobs: 1,
  },
  playhouse: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 150,
    upgradeBaseCost: 175,
    maxLevel: 3,
    happinessBonus: 7,
    leisureSpot: true,
  },
  school: {
    ...NO_OUTPUT,
    category: 'science',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 5,
    buildCost: 160,
    upgradeBaseCost: 185,
    maxLevel: 4,
    research: 0.6,
    jobs: 2,
    happinessBonus: 1,
  },
  infirmary: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 6,
    buildCost: 170,
    upgradeBaseCost: 195,
    maxLevel: 4,
    happinessBonus: 5,
    jobs: 2,
  },
  cistern: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'medieval',
    cityLevel: 4,
    buildCost: 80,
    upgradeBaseCost: 90,
    maxLevel: 3,
    happinessBonus: 3,
  },
  tenement: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 60,
    upgradeBaseCost: 70,
    maxLevel: 4,
    populationCapacity: 8,
  },
  dormitory: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 90,
    upgradeBaseCost: 100,
    maxLevel: 4,
    populationCapacity: 11,
  },
  cannery: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 130,
    upgradeBaseCost: 150,
    maxLevel: 4,
    goldPerSecond: 2,
    jobs: 4,
    populationCapacity: 3,
    powerDemand: 1,
  },
  dairy: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 5,
    buildCost: 100,
    upgradeBaseCost: 115,
    maxLevel: 4,
    goldPerSecond: 1.4,
    jobs: 2,
    populationCapacity: 2,
  },
  grainElevator: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 150,
    upgradeBaseCost: 170,
    maxLevel: 4,
    populationCapacity: 9,
    jobs: 2,
  },
  generalStore: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 5,
    buildCost: 110,
    upgradeBaseCost: 125,
    maxLevel: 4,
    goldPerSecond: 1.6,
    jobs: 3,
  },
  bank: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 260,
    upgradeBaseCost: 300,
    maxLevel: 4,
    goldPerSecond: 3,
    jobs: 4,
    powerDemand: 1,
  },
  postOffice: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 160,
    upgradeBaseCost: 180,
    maxLevel: 4,
    goldPerSecond: 1.2,
    jobs: 3,
    happinessBonus: 2,
  },
  pub: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 5,
    buildCost: 120,
    upgradeBaseCost: 135,
    maxLevel: 4,
    goldPerSecond: 1.5,
    jobs: 2,
    happinessBonus: 2,
    leisureSpot: true,
  },
  sawmill: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 5,
    buildCost: 140,
    upgradeBaseCost: 160,
    maxLevel: 4,
    goldPerSecond: 1.8,
    jobs: 4,
    powerDemand: 1,
  },
  textileMill: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 200,
    upgradeBaseCost: 230,
    maxLevel: 4,
    goldPerSecond: 2.4,
    jobs: 6,
    powerDemand: 2,
  },
  brickWorks: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 180,
    upgradeBaseCost: 210,
    maxLevel: 4,
    goldPerSecond: 2,
    jobs: 4,
    powerDemand: 1,
    pollution: 0.5,
  },
  steelMill: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 8,
    buildCost: 420,
    upgradeBaseCost: 480,
    maxLevel: 4,
    goldPerSecond: 4,
    jobs: 9,
    powerDemand: 4,
    pollution: 1,
  },
  shipyard: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 9,
    buildCost: 520,
    upgradeBaseCost: 600,
    maxLevel: 3,
    goldPerSecond: 4.5,
    jobs: 9,
    powerDemand: 3,
  },
  coalPlant: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 240,
    upgradeBaseCost: 280,
    maxLevel: 4,
    powerSupply: 16,
    jobs: 3,
    pollution: 1,
  },
  gasWorks: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 220,
    upgradeBaseCost: 250,
    maxLevel: 4,
    powerSupply: 12,
    jobs: 3,
    pollution: 0.5,
  },
  sewageWorks: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 230,
    upgradeBaseCost: 260,
    maxLevel: 4,
    happinessBonus: 6,
    jobs: 2,
    powerDemand: 1,
  },
  clinic: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 190,
    upgradeBaseCost: 215,
    maxLevel: 4,
    happinessBonus: 5,
    jobs: 2,
    powerDemand: 1,
  },
  trainStation: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    goldPerSecond: 2,
    jobs: 4,
    happinessBonus: 4,
    powerDemand: 1,
  },
  tramStop: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 90,
    upgradeBaseCost: 100,
    maxLevel: 2,
    happinessBonus: 3,
  },
  freightDepot: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 260,
    upgradeBaseCost: 300,
    maxLevel: 4,
    goldPerSecond: 2.2,
    jobs: 4,
    powerDemand: 1,
  },
  promenade: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 120,
    upgradeBaseCost: 140,
    maxLevel: 3,
    happinessBonus: 5,
    leisureSpot: true,
  },
  musicHall: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 340,
    upgradeBaseCost: 390,
    maxLevel: 3,
    happinessBonus: 8,
    jobs: 2,
    powerDemand: 1,
    leisureSpot: true,
  },
  newspaper: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 6,
    buildCost: 210,
    upgradeBaseCost: 240,
    maxLevel: 4,
    goldPerSecond: 1,
    jobs: 3,
    happinessBonus: 4,
    powerDemand: 1,
  },
  observatory: {
    ...NO_OUTPUT,
    category: 'science',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 7,
    buildCost: 320,
    upgradeBaseCost: 360,
    maxLevel: 4,
    research: 1.2,
    jobs: 2,
    powerDemand: 1,
  },
  highRise: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 320,
    upgradeBaseCost: 360,
    maxLevel: 5,
    populationCapacity: 16,
    goldPerSecond: 1,
    powerDemand: 2,
  },
  townhouseRow: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 180,
    upgradeBaseCost: 200,
    maxLevel: 4,
    populationCapacity: 10,
    happinessBonus: 1,
  },
  studioBlock: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 220,
    upgradeBaseCost: 250,
    maxLevel: 5,
    populationCapacity: 12,
  },
  ecoHousing: {
    ...NO_OUTPUT,
    category: 'housing',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    populationCapacity: 12,
    happinessBonus: 3,
  },
  verticalFarm: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 340,
    upgradeBaseCost: 380,
    maxLevel: 5,
    populationCapacity: 12,
    jobs: 4,
    powerDemand: 3,
  },
  greenhouse: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 150,
    upgradeBaseCost: 170,
    maxLevel: 4,
    populationCapacity: 6,
    jobs: 2,
    powerDemand: 1,
  },
  fishFarm: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 200,
    upgradeBaseCost: 230,
    maxLevel: 4,
    goldPerSecond: 2.5,
    jobs: 3,
    powerDemand: 1,
  },
  foodMarket: {
    ...NO_OUTPUT,
    category: 'food',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 240,
    upgradeBaseCost: 270,
    maxLevel: 4,
    goldPerSecond: 2.8,
    jobs: 5,
    powerDemand: 1,
  },
  supermarket: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    goldPerSecond: 3.5,
    jobs: 6,
    powerDemand: 2,
  },
  shoppingMall: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 620,
    upgradeBaseCost: 700,
    maxLevel: 4,
    goldPerSecond: 5,
    jobs: 9,
    powerDemand: 3,
    happinessBonus: 2,
  },
  cafe: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 7,
    buildCost: 140,
    upgradeBaseCost: 160,
    maxLevel: 4,
    goldPerSecond: 1.8,
    jobs: 2,
    happinessBonus: 2,
    leisureSpot: true,
  },
  officeTower: {
    ...NO_OUTPUT,
    category: 'commerce',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 560,
    upgradeBaseCost: 640,
    maxLevel: 5,
    goldPerSecond: 5.5,
    jobs: 11,
    powerDemand: 3,
  },
  recyclingCenter: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 280,
    upgradeBaseCost: 320,
    maxLevel: 4,
    goldPerSecond: 2,
    jobs: 4,
    happinessBonus: 2,
    powerDemand: 2,
  },
  carPlant: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 700,
    upgradeBaseCost: 800,
    maxLevel: 4,
    goldPerSecond: 6,
    jobs: 11,
    powerDemand: 5,
    pollution: 0.5,
  },
  dataCenter: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 640,
    upgradeBaseCost: 720,
    maxLevel: 4,
    goldPerSecond: 4,
    jobs: 4,
    research: 0.8,
    powerDemand: 6,
  },
  semiconductorFab: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 11,
    buildCost: 900,
    upgradeBaseCost: 1000,
    maxLevel: 4,
    goldPerSecond: 7,
    jobs: 11,
    powerDemand: 6,
  },
  windFarm: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 320,
    upgradeBaseCost: 360,
    maxLevel: 4,
    powerSupply: 18,
    jobs: 1,
  },
  hydroPlant: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 480,
    upgradeBaseCost: 540,
    maxLevel: 4,
    powerSupply: 24,
    jobs: 3,
  },
  geothermalPlant: {
    ...NO_OUTPUT,
    category: 'energy',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 620,
    upgradeBaseCost: 700,
    maxLevel: 4,
    powerSupply: 28,
    jobs: 3,
  },
  hospital: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 560,
    upgradeBaseCost: 640,
    maxLevel: 4,
    happinessBonus: 9,
    jobs: 7,
    powerDemand: 3,
  },
  airTower: {
    ...NO_OUTPUT,
    category: 'utility',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 420,
    upgradeBaseCost: 480,
    maxLevel: 3,
    happinessBonus: 6,
    powerDemand: 2,
  },
  busTerminal: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    goldPerSecond: 1,
    jobs: 4,
    happinessBonus: 5,
    powerDemand: 1,
  },
  subwayStation: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 420,
    upgradeBaseCost: 480,
    maxLevel: 4,
    jobs: 3,
    happinessBonus: 7,
    powerDemand: 2,
  },
  bikeLane: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 7,
    buildCost: 20,
    upgradeBaseCost: 0,
    maxLevel: 1,
    happinessBonus: 1,
  },
  airport: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 11,
    buildCost: 1200,
    upgradeBaseCost: 1400,
    maxLevel: 3,
    goldPerSecond: 6,
    jobs: 12,
    happinessBonus: 4,
    powerDemand: 4,
  },
  playground: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 7,
    buildCost: 90,
    upgradeBaseCost: 100,
    maxLevel: 3,
    happinessBonus: 4,
    leisureSpot: true,
  },
  swimmingPool: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 260,
    upgradeBaseCost: 300,
    maxLevel: 4,
    happinessBonus: 7,
    jobs: 2,
    powerDemand: 1,
    leisureSpot: true,
  },
  cinema: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 320,
    upgradeBaseCost: 360,
    maxLevel: 4,
    goldPerSecond: 1.5,
    jobs: 3,
    happinessBonus: 6,
    powerDemand: 2,
    leisureSpot: true,
  },
  stadium: {
    ...NO_OUTPUT,
    category: 'leisure',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 900,
    upgradeBaseCost: 1000,
    maxLevel: 3,
    happinessBonus: 12,
    jobs: 7,
    powerDemand: 3,
    goldPerSecond: 2,
  },
  museum: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 520,
    upgradeBaseCost: 600,
    maxLevel: 4,
    happinessBonus: 9,
    jobs: 3,
    powerDemand: 1,
  },
  publicLibrary: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 360,
    upgradeBaseCost: 410,
    maxLevel: 4,
    happinessBonus: 4,
    research: 1,
    jobs: 3,
    powerDemand: 1,
  },
  artsCenter: {
    ...NO_OUTPUT,
    category: 'culture',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 9,
    buildCost: 440,
    upgradeBaseCost: 500,
    maxLevel: 4,
    happinessBonus: 8,
    jobs: 3,
    powerDemand: 2,
    leisureSpot: true,
  },
  university: {
    ...NO_OUTPUT,
    category: 'science',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 800,
    upgradeBaseCost: 900,
    maxLevel: 4,
    research: 3,
    jobs: 9,
    powerDemand: 3,
    happinessBonus: 3,
  },
  spaceCenter: {
    ...NO_OUTPUT,
    category: 'science',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 12,
    buildCost: 1600,
    upgradeBaseCost: 1800,
    maxLevel: 3,
    research: 4,
    jobs: 9,
    powerDemand: 6,
    happinessBonus: 5,
  },
  fireStation: {
    ...NO_OUTPUT,
    category: 'civic',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    happinessBonus: 5,
    jobs: 4,
    powerDemand: 1,
  },
  policeStation: {
    ...NO_OUTPUT,
    category: 'civic',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 8,
    buildCost: 300,
    upgradeBaseCost: 340,
    maxLevel: 4,
    happinessBonus: 5,
    jobs: 4,
    powerDemand: 1,
  },
  courthouse: {
    ...NO_OUTPUT,
    category: 'civic',
    buildable: true,
    movable: true,
    era: 'modern',
    cityLevel: 10,
    buildCost: 620,
    upgradeBaseCost: 700,
    maxLevel: 3,
    happinessBonus: 6,
    jobs: 5,
    powerDemand: 2,
  },
  railway: {
    ...NO_OUTPUT,
    category: 'transport',
    // Laid by the railway project, not from the build menu.
    buildable: false,
    movable: false,
    era: 'industrial',
    cityLevel: 1,
    buildCost: 0,
    upgradeBaseCost: 0,
    maxLevel: 1,
    happinessBonus: 0.4,
    goldPerSecond: 0.2,
  },
  road: {
    ...NO_OUTPUT,
    category: 'transport',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 1,
    buildCost: 8,
    upgradeBaseCost: 0,
    maxLevel: 1,
  },
  factory: {
    ...NO_OUTPUT,
    category: 'industry',
    buildable: true,
    movable: true,
    era: 'industrial',
    cityLevel: 1,
    buildCost: 150,
    upgradeBaseCost: 220,
    maxLevel: 5,
    goldPerSecond: 5,
    jobs: 8,
    powerDemand: 4,
    pollution: 1,
  },
};

/**
 * Keeping the past (Phase 2 §11): when the city enters a new era, its oldest corner stays as
 * it was, so a walk through the city is also a walk through its history.
 */
export const HERITAGE = {
  /** Oldest buildings kept in their original era when an era begins. */
  autoCount: 5,
} as const;

/**
 * Large projects (Phase 2 §8): the player commissions them, and then they take time, so the
 * city visibly has work going on. None of them can fail — they only take a while.
 */
export type ProjectKind = 'railway' | 'tunnel' | 'centralPark';

export const PROJECTS: Record<ProjectKind, { cost: number; workSeconds: number; era: EraId; cityLevel: number }> = {
  centralPark: { cost: 600, workSeconds: 60, era: 'medieval', cityLevel: 5 },
  tunnel: { cost: 700, workSeconds: 75, era: 'industrial', cityLevel: 6 },
  railway: { cost: 900, workSeconds: 90, era: 'industrial', cityLevel: 7 },
};

/** Walking routes: citizens keep off the carriageway and cross at crossings. */
export const PATHS = {
  /** Tiles a single route search may look at before giving up. */
  maxTilesSearched: 1200,
} as const;

/** Traffic lights at junctions (see world/signals.ts). */
export const SIGNALS = {
  /** Seconds of green for each direction. */
  carPhaseSeconds: 9,
  /** Seconds when everything stops and people cross. */
  walkPhaseSeconds: 6,
  /** Junctions are shifted by a multiple of this, so the city does not blink in unison. */
  offsetSeconds: 5,
  /** A zebra crossing away from a junction has its own, simpler two-step cycle. */
  crossingCarSeconds: 12,
  crossingWalkSeconds: 7,
} as const;

/** Roads: how wide they can read as, and how often people can cross them. */
export const ROADS = {
  /** Tiles of width the markings distinguish (3 means "three or more"). */
  maxWidth: 3,
  /** A crossing every this many tiles along a road, plus every junction. */
  crossingSpacing: 4,
  /** How far along a road to look when working out which way it runs. */
  maxRun: 6,
} as const;

/** The rocky ridges crossing the map (see world/terrain.ts). */
export const TERRAIN = {
  ridges: 3,
  /** Half-width of a ridge, in tiles. */
  ridgeWidth: 1.6,
  /** How much a ridge wanders. */
  ridgeWobble: 2.2,
  /** Tiles around the starting territory that are always clear. */
  clearMargin: 3,
} as const;

export const TERRITORY = {
  /** Side length (tiles) of the square territory unlocked at the start. */
  initialSize: 10,
  /** Tiles added on every side per expansion. */
  expansionStep: 2,
  expansionBaseCost: 120,
  /** Each expansion costs this many times the previous one. */
  expansionCostGrowth: 1.9,
} as const;

/**
 * "AI consulting" (AI 컨설팅): the thresholds it reads the city by, and how many options it
 * offers. It only ever suggests — the player decides (Phase 2 §6).
 */
export const CONSULTING = {
  /** Homes are "full" at this share of capacity. */
  housingFullShare: 0.8,
  /** Jobs wanted per citizen. */
  jobsPerCitizen: 0.8,
  parksPerHouse: 0.2,
  /** Below this happiness it suggests something cheerful. */
  happinessBelow: 62,
  /** Free tiles at which it starts talking about more land. */
  roomRunningOutTiles: 8,
  /** Gold sitting unused that is worth mentioning. */
  idleGold: 2000,
  /** Candidate places offered per kind of plan. */
  candidateSpots: 3,
  /** Minimum distance between two candidates, in tiles. */
  spotSpacing: 4,
  maxProposals: 4,
} as const;

/** Thank-you gold for reaching an achievement. Small enough to stay a nice surprise. */
export const ACHIEVEMENTS_REWARD = {
  small: 25,
  medium: 120,
  large: 400,
} as const;

/**
 * Small happy things that drop in now and then. Every event is a gift: nothing here can set
 * the city back.
 */
export const EVENTS = {
  /** Seconds between events, picked at random in this range. */
  intervalSeconds: [110, 220] as const,
  /** The city stays quiet until it has at least this many buildings. */
  minBuildings: 3,
  /** A merchant pays about this many seconds of the city's income... */
  merchantIncomeSeconds: 60,
  /** ...but never less than this. */
  merchantMinGold: 30,
  /** Citizens who move in after a good harvest (never above housing). */
  harvestCitizens: 4,
  /** Mood lift for every citizen at a festival. */
  festivalHappiness: 12,
  /** Research points a wandering scholar contributes. */
  scholarPoints: 30,
} as const;

/**
 * How fast the city grows. This is a comfort setting, not a difficulty: it changes speed only,
 * never the chance of anything going wrong (design brief Phase 2 §3).
 */
export type GrowthPace = 'relaxed' | 'standard' | 'fast';

export const GROWTH_PACE: Record<GrowthPace, {
  /** Multiplier on gold and research output. */
  output: number;
  /** Multiplier on population growth. */
  population: number;
  research: number;
  /** Multiplier on the advisor's waiting time (lower acts more often). */
  advisorInterval: number;
}> = {
  relaxed: { output: 0.7, population: 0.7, research: 0.75, advisorInterval: 1.6 },
  standard: { output: 1, population: 1, research: 1, advisorInterval: 1 },
  fast: { output: 1.6, population: 1.5, research: 1.6, advisorInterval: 0.6 },
};

/**
 * How much the advisor is allowed to do (Phase 2 §7-8). Small things may be automatic; the
 * big ones — where the city grows, large projects, entering an era — stay with the player.
 */
export type AutoLevel = 'off' | 'low' | 'medium' | 'high';

export const AUTO_LEVELS: Record<AutoLevel, {
  /** Whether the advisor builds at all ('low' only offers advice). */
  acts: boolean;
  intervalMultiplier: number;
  /** Share of gold it leaves untouched. */
  goldReserve: number;
  allowUpgrade: boolean;
  allowResearch: boolean;
  /** Widening the territory is a player decision except at the highest level. */
  allowExpand: boolean;
}> = {
  off: { acts: false, intervalMultiplier: 1, goldReserve: 1, allowUpgrade: false, allowResearch: false, allowExpand: false },
  low: { acts: false, intervalMultiplier: 1.4, goldReserve: 0.5, allowUpgrade: false, allowResearch: false, allowExpand: false },
  medium: { acts: true, intervalMultiplier: 1, goldReserve: 0.35, allowUpgrade: true, allowResearch: true, allowExpand: false },
  high: { acts: true, intervalMultiplier: 0.6, goldReserve: 0.2, allowUpgrade: true, allowResearch: true, allowExpand: true },
};

/**
 * The optional "auto-grow" advisor: it tends the city on its own, slower than a player and
 * always leaving gold to spend, so watching it is relaxing rather than a replacement.
 */
export const AUTO_GROW = {
  /** Seconds between advisor actions. */
  intervalSeconds: 14,
  /** Share of gold the advisor never touches. */
  goldReserve: 0.35,
  /** An upgrade may use at most this share of the advisor's budget. */
  upgradeBudgetShare: 0.5,
  /** Build homes once the population reaches this share of housing. */
  housingFullShare: 0.75,
  /** Parks the advisor aims for per home. */
  parksPerHouse: 0.25,
  /** Farms the advisor aims for per home (they feed the city). */
  farmsPerHouse: 0.5,
  /** Below this city happiness the advisor builds something cheerful. */
  happinessTarget: 60,
  /** Expand only when the territory is nearly full. */
  expandWhenFreeTilesAtMost: 4,
  /** How strongly neighbour bonuses pull a new building towards a tile. */
  adjacencyWeight: 1.5,
  /** Actions credited for time away, at most. */
  maxOfflineActions: 8,
} as const;

/**
 * Progress while the game is closed or the tab is hidden (design brief: capped, resources
 * only — no research, XP or events).
 */
export const OFFLINE = {
  maxSeconds: 8 * 60 * 60,
  /** Shorter gaps are simply simulated as normal ticks, without a report. */
  minReportSeconds: 60,
  /** Offline production is integrated in steps of this length. */
  stepSeconds: 60,
  /** Share of normal production earned while away. */
  efficiency: 1,
} as const;
