import type { BuildingType } from '../building/types';
import type { ModelSpec } from './modelSpec';

/**
 * Model specs for buildings without a hand-made model. The twelve original types are modelled
 * by hand for the first three eras, and roads and railways follow their neighbours (see
 * models.ts); everything else describes itself here.
 */
export const BUILDING_SPECS: Partial<Record<BuildingType, ModelSpec>> = {
  granary: {
    width: 0.6,
    depth: 0.5,
    height: 0.32,
    heightPerLevel: 0.04,
    wall: 'wood',
    plinth: 'stone',
    roof: 'gable',
    roofColor: 'thatch',
    platform: 'soil',
    props: ['door', 'crates'],
  },
  fishingHut: {
    width: 0.56,
    depth: 0.48,
    height: 0.3,
    heightPerLevel: 0.03,
    shape: 'openShed',
    wall: 'wood',
    plinth: 'woodDark',
    roof: 'gable',
    roofColor: 'thatch',
    platform: 'wood',
    props: ['pond', 'crates'],
  },
  hunterLodge: {
    width: 0.58,
    depth: 0.5,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'mud',
    roof: 'pyramid',
    roofColor: 'thatch',
    props: ['door', 'fence'],
  },
  orchard: {
    width: 0.5,
    depth: 0.42,
    height: 0.04,
    wall: 'parkGrass',
    roof: 'none',
    platform: 'parkGrass',
    props: ['trees', 'fence'],
  },
  potteryKiln: {
    width: 0.44,
    depth: 0.44,
    height: 0.3,
    heightPerLevel: 0.04,
    shape: 'cylinder',
    wall: 'mud',
    roof: 'cone',
    roofColor: 'brickDark',
    platform: 'soil',
    props: ['chimney', 'crates'],
  },
  weaversHouse: {
    width: 0.6,
    depth: 0.5,
    height: 0.32,
    heightPerLevel: 0.04,
    wall: 'plaster',
    plinth: 'wood',
    roof: 'gable',
    roofColor: 'thatch',
    props: ['awning', 'door'],
  },
  quarry: {
    width: 0.66,
    depth: 0.56,
    height: 0.16,
    heightPerLevel: 0.03,
    shape: 'slab',
    wall: 'stone',
    roof: 'none',
    platform: 'stone',
    props: ['crates', 'fence'],
  },
  tradingPost: {
    width: 0.64,
    depth: 0.52,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'wood',
    roof: 'gable',
    roofColor: 'cloth',
    props: ['awning', 'sign', 'crates'],
  },
  campfire: {
    width: 0.2,
    depth: 0.2,
    height: 0.07,
    shape: 'cylinder',
    wall: 'stone',
    roof: 'none',
    platform: 'soil',
    props: ['benches'],
  },
  storyGround: {
    width: 0.34,
    depth: 0.3,
    height: 0.05,
    wall: 'path',
    roof: 'none',
    platform: 'path',
    props: ['benches', 'trees'],
  },
  herbalist: {
    width: 0.54,
    depth: 0.46,
    height: 0.3,
    heightPerLevel: 0.03,
    wall: 'mud',
    roof: 'pyramid',
    roofColor: 'thatch',
    props: ['crops', 'door'],
  },
  watchtower: {
    width: 0.34,
    depth: 0.34,
    height: 0.6,
    heightPerLevel: 0.1,
    shape: 'tower',
    wall: 'wood',
    plinth: 'stone',
    roof: 'pyramid',
    roofColor: 'thatch',
    props: ['flagpole'],
  },
  bakery: {
    width: 0.62,
    depth: 0.52,
    height: 0.34,
    heightPerLevel: 0.05,
    wall: 'plaster',
    plinth: 'stone',
    roof: 'gable',
    roofColor: 'tileRoof',
    props: ['awning', 'chimney', 'windows'],
  },
  brewery: {
    width: 0.66,
    depth: 0.54,
    height: 0.36,
    heightPerLevel: 0.05,
    wall: 'stone',
    roof: 'gable',
    roofColor: 'slate',
    props: ['crates', 'sign', 'door'],
  },
  marketSquare: {
    width: 0.5,
    depth: 0.44,
    height: 0.05,
    wall: 'path',
    roof: 'none',
    platform: 'path',
    props: ['crates', 'benches', 'sign'],
  },
  guildHall: {
    width: 0.74,
    depth: 0.6,
    height: 0.42,
    heightPerLevel: 0.06,
    wall: 'hallWall',
    plinth: 'stone',
    roof: 'gable',
    roofColor: 'hallRoof',
    props: ['columns', 'windows', 'sign'],
  },
  flourMill: {
    width: 0.6,
    depth: 0.52,
    height: 0.38,
    heightPerLevel: 0.05,
    wall: 'stone',
    roof: 'gable',
    roofColor: 'tileRoof',
    props: ['chimney', 'crates', 'door'],
  },
  warehouse: {
    width: 0.76,
    depth: 0.56,
    height: 0.32,
    heightPerLevel: 0.04,
    shape: 'slab',
    wall: 'wood',
    plinth: 'stone',
    roof: 'gable',
    roofColor: 'slate',
    props: ['door', 'crates'],
  },
  stonemason: {
    width: 0.66,
    depth: 0.56,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'stone',
    roof: 'flat',
    roofColor: 'slate',
    platform: 'stone',
    props: ['crates', 'fence'],
  },
  stable: {
    width: 0.7,
    depth: 0.54,
    height: 0.3,
    heightPerLevel: 0.04,
    shape: 'openShed',
    wall: 'wood',
    plinth: 'woodDark',
    roof: 'gable',
    roofColor: 'thatch',
    platform: 'soil',
    props: ['fence', 'crates'],
  },
  bathhouse: {
    width: 0.62,
    depth: 0.54,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'stone',
    roof: 'dome',
    roofColor: 'dome',
    props: ['pond', 'door'],
  },
  playhouse: {
    width: 0.56,
    depth: 0.46,
    height: 0.16,
    wall: 'wood',
    roof: 'none',
    platform: 'path',
    props: ['benches', 'flagpole'],
  },
  school: {
    width: 0.66,
    depth: 0.54,
    height: 0.36,
    heightPerLevel: 0.05,
    wall: 'plaster',
    plinth: 'stone',
    roof: 'gable',
    roofColor: 'tileRoof',
    props: ['windows', 'clock', 'door'],
  },
  infirmary: {
    width: 0.68,
    depth: 0.56,
    height: 0.34,
    heightPerLevel: 0.05,
    wall: 'plaster',
    roof: 'gable',
    roofColor: 'slate',
    props: ['windows', 'door', 'lamps'],
  },
  cistern: {
    width: 0.46,
    depth: 0.46,
    height: 0.26,
    heightPerLevel: 0.03,
    shape: 'cylinder',
    wall: 'stone',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'stone',
    props: ['pipes', 'pond'],
  },
  tenement: {
    width: 0.6,
    depth: 0.5,
    height: 0.62,
    heightPerLevel: 0.14,
    wall: 'brick',
    plinth: 'stone',
    roof: 'flat',
    roofColor: 'slate',
    props: ['windows', 'door', 'chimney'],
  },
  dormitory: {
    width: 0.74,
    depth: 0.52,
    height: 0.56,
    heightPerLevel: 0.12,
    shape: 'slab',
    wall: 'plaster',
    plinth: 'brick',
    roof: 'gable',
    roofColor: 'slate',
    props: ['windows', 'door'],
  },
  cannery: {
    width: 0.72,
    depth: 0.58,
    height: 0.38,
    heightPerLevel: 0.05,
    wall: 'plaster',
    roof: 'sawtooth',
    roofColor: 'slate',
    props: ['windowBand', 'crates', 'vents'],
  },
  dairy: {
    width: 0.68,
    depth: 0.54,
    height: 0.32,
    heightPerLevel: 0.04,
    wall: 'white',
    plinth: 'wood',
    roof: 'gable',
    roofColor: 'clothRed',
    platform: 'soil',
    props: ['fence', 'door', 'crates'],
  },
  grainElevator: {
    width: 0.4,
    depth: 0.44,
    height: 0.52,
    heightPerLevel: 0.08,
    shape: 'cylinder',
    wall: 'concrete',
    roof: 'cone',
    roofColor: 'slate',
    platform: 'concrete',
    props: ['silo', 'crates'],
  },
  generalStore: {
    width: 0.64,
    depth: 0.52,
    height: 0.4,
    heightPerLevel: 0.05,
    wall: 'brick',
    roof: 'flat',
    roofColor: 'slate',
    props: ['awning', 'windowBand', 'sign'],
  },
  bank: {
    width: 0.7,
    depth: 0.58,
    height: 0.46,
    heightPerLevel: 0.06,
    wall: 'stone',
    roof: 'flat',
    roofColor: 'slate',
    props: ['columns', 'stairs', 'lamps'],
  },
  postOffice: {
    width: 0.66,
    depth: 0.54,
    height: 0.42,
    heightPerLevel: 0.05,
    wall: 'plaster',
    plinth: 'brick',
    roof: 'gable',
    roofColor: 'tileRoof',
    props: ['windows', 'sign', 'door', 'clock'],
  },
  pub: {
    width: 0.6,
    depth: 0.5,
    height: 0.38,
    heightPerLevel: 0.05,
    wall: 'brickDark',
    roof: 'gable',
    roofColor: 'slate',
    props: ['awning', 'sign', 'windows', 'lamps'],
  },
  sawmill: {
    width: 0.74,
    depth: 0.58,
    height: 0.32,
    heightPerLevel: 0.04,
    shape: 'slab',
    wall: 'wood',
    plinth: 'stone',
    roof: 'sawtooth',
    roofColor: 'roofDark',
    props: ['crates', 'vents'],
  },
  textileMill: {
    width: 0.78,
    depth: 0.6,
    height: 0.46,
    heightPerLevel: 0.06,
    wall: 'brick',
    roof: 'sawtooth',
    roofColor: 'slate',
    props: ['windowBand', 'stack', 'vents'],
  },
  brickWorks: {
    width: 0.72,
    depth: 0.58,
    height: 0.34,
    heightPerLevel: 0.05,
    wall: 'brickDark',
    roof: 'flat',
    roofColor: 'roofDark',
    platform: 'soil',
    props: ['stack', 'crates'],
  },
  steelMill: {
    width: 0.84,
    depth: 0.66,
    height: 0.48,
    heightPerLevel: 0.06,
    wall: 'iron',
    plinth: 'brickDark',
    roof: 'sawtooth',
    roofColor: 'roofDark',
    props: ['stack', 'pipes', 'vents', 'crates'],
  },
  shipyard: {
    width: 0.86,
    depth: 0.64,
    height: 0.4,
    heightPerLevel: 0.05,
    shape: 'openShed',
    wall: 'iron',
    plinth: 'iron',
    roof: 'arch',
    roofColor: 'slate',
    platform: 'concrete',
    props: ['crates', 'pipes'],
  },
  coalPlant: {
    width: 0.76,
    depth: 0.62,
    height: 0.42,
    heightPerLevel: 0.05,
    wall: 'brick',
    roof: 'flat',
    roofColor: 'roofDark',
    props: ['stack', 'vents', 'pipes'],
  },
  gasWorks: {
    width: 0.5,
    depth: 0.5,
    height: 0.36,
    heightPerLevel: 0.05,
    shape: 'cylinder',
    wall: 'iron',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['pipes', 'tank'],
  },
  sewageWorks: {
    width: 0.78,
    depth: 0.6,
    height: 0.18,
    heightPerLevel: 0.02,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'concrete',
    platform: 'concrete',
    props: ['tank', 'pipes', 'pond'],
  },
  clinic: {
    width: 0.64,
    depth: 0.54,
    height: 0.38,
    heightPerLevel: 0.05,
    wall: 'white',
    plinth: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['windows', 'door', 'lamps'],
  },
  trainStation: {
    width: 0.8,
    depth: 0.56,
    height: 0.4,
    heightPerLevel: 0.05,
    wall: 'brick',
    plinth: 'stone',
    roof: 'arch',
    roofColor: 'iron',
    platform: 'path',
    props: ['rails', 'clock', 'lamps'],
  },
  tramStop: {
    width: 0.3,
    depth: 0.26,
    height: 0.1,
    wall: 'iron',
    roof: 'none',
    platform: 'path',
    props: ['shelter', 'rails', 'lamps'],
  },
  freightDepot: {
    width: 0.82,
    depth: 0.58,
    height: 0.3,
    heightPerLevel: 0.04,
    shape: 'slab',
    wall: 'iron',
    roof: 'flat',
    roofColor: 'roofDark',
    platform: 'concrete',
    props: ['rails', 'crates', 'vents'],
  },
  promenade: {
    width: 0.5,
    depth: 0.34,
    height: 0.05,
    wall: 'path',
    roof: 'none',
    platform: 'path',
    props: ['trees', 'benches', 'lamps'],
  },
  musicHall: {
    width: 0.74,
    depth: 0.6,
    height: 0.44,
    heightPerLevel: 0.06,
    wall: 'hallWall',
    plinth: 'stone',
    roof: 'dome',
    roofColor: 'dome',
    props: ['columns', 'lamps', 'stairs'],
  },
  newspaper: {
    width: 0.66,
    depth: 0.54,
    height: 0.44,
    heightPerLevel: 0.06,
    wall: 'brick',
    roof: 'flat',
    roofColor: 'slate',
    props: ['windows', 'sign', 'vents'],
  },
  observatory: {
    width: 0.5,
    depth: 0.5,
    height: 0.36,
    heightPerLevel: 0.05,
    shape: 'cylinder',
    wall: 'plaster',
    roof: 'dome',
    roofColor: 'iron',
    platform: 'stone',
    props: ['door', 'stairs'],
  },
  highRise: {
    width: 0.56,
    depth: 0.5,
    height: 1.1,
    heightPerLevel: 0.22,
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    props: ['balconies', 'glassFront', 'antenna'],
  },
  townhouseRow: {
    width: 0.8,
    depth: 0.5,
    height: 0.44,
    heightPerLevel: 0.1,
    shape: 'slab',
    wall: 'plaster',
    plinth: 'brick',
    roof: 'gable',
    roofColor: 'tileRoof',
    props: ['windows', 'door', 'trees'],
  },
  studioBlock: {
    width: 0.58,
    depth: 0.5,
    height: 0.8,
    heightPerLevel: 0.16,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['windows', 'door', 'vents'],
  },
  ecoHousing: {
    width: 0.66,
    depth: 0.52,
    height: 0.5,
    heightPerLevel: 0.12,
    wall: 'wood',
    plinth: 'plaster',
    roof: 'flat',
    roofColor: 'parkGrass',
    props: ['solar', 'windows', 'trees'],
  },
  verticalFarm: {
    width: 0.6,
    depth: 0.52,
    height: 0.78,
    heightPerLevel: 0.16,
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['glassFront', 'solar', 'vents'],
  },
  greenhouse: {
    width: 0.8,
    depth: 0.6,
    height: 0.16,
    wall: 'glass',
    roof: 'arch',
    roofColor: 'glass',
    platform: 'soil',
    props: ['crops'],
  },
  fishFarm: {
    width: 0.8,
    depth: 0.62,
    height: 0.14,
    wall: 'concrete',
    roof: 'none',
    platform: 'concrete',
    props: ['pond', 'tank', 'pipes'],
  },
  foodMarket: {
    width: 0.84,
    depth: 0.62,
    height: 0.3,
    heightPerLevel: 0.04,
    shape: 'slab',
    wall: 'plaster',
    roof: 'arch',
    roofColor: 'iron',
    platform: 'path',
    props: ['crates', 'awning', 'lamps'],
  },
  supermarket: {
    width: 0.86,
    depth: 0.64,
    height: 0.36,
    heightPerLevel: 0.05,
    shape: 'slab',
    wall: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    platform: 'path',
    props: ['glassFront', 'sign', 'lamps'],
  },
  shoppingMall: {
    width: 0.88,
    depth: 0.68,
    height: 0.5,
    heightPerLevel: 0.08,
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['glassFront', 'sign', 'lamps', 'vents'],
  },
  cafe: {
    width: 0.56,
    depth: 0.48,
    height: 0.32,
    heightPerLevel: 0.04,
    wall: 'wood',
    roof: 'flat',
    roofColor: 'slate',
    props: ['awning', 'glassFront', 'benches'],
  },
  officeTower: {
    width: 0.52,
    depth: 0.48,
    height: 1.2,
    heightPerLevel: 0.24,
    shape: 'tower',
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['windowBand', 'antenna', 'lamps'],
  },
  recyclingCenter: {
    width: 0.8,
    depth: 0.62,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'concrete',
    roof: 'sawtooth',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['crates', 'vents', 'pipes'],
  },
  carPlant: {
    width: 0.88,
    depth: 0.68,
    height: 0.42,
    heightPerLevel: 0.05,
    shape: 'slab',
    wall: 'iron',
    plinth: 'concrete',
    roof: 'sawtooth',
    roofColor: 'roofDark',
    props: ['vents', 'pipes', 'crates'],
  },
  dataCenter: {
    width: 0.78,
    depth: 0.62,
    height: 0.34,
    heightPerLevel: 0.04,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['vents', 'dish', 'tank'],
  },
  semiconductorFab: {
    width: 0.86,
    depth: 0.66,
    height: 0.46,
    heightPerLevel: 0.06,
    wall: 'white',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['windowBand', 'vents', 'pipes', 'tank'],
  },
  windFarm: {
    width: 0.24,
    depth: 0.24,
    height: 0.9,
    heightPerLevel: 0.12,
    shape: 'tower',
    wall: 'white',
    roof: 'none',
    platform: 'parkGrass',
    props: ['antenna'],
  },
  hydroPlant: {
    width: 0.84,
    depth: 0.6,
    height: 0.3,
    heightPerLevel: 0.04,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'concrete',
    platform: 'concrete',
    props: ['pond', 'pipes', 'vents'],
  },
  geothermalPlant: {
    width: 0.7,
    depth: 0.58,
    height: 0.32,
    heightPerLevel: 0.04,
    wall: 'iron',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['pipes', 'tank', 'vents'],
  },
  hospital: {
    width: 0.8,
    depth: 0.62,
    height: 0.62,
    heightPerLevel: 0.1,
    wall: 'white',
    plinth: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['windows', 'glassFront', 'lamps', 'dish'],
  },
  airTower: {
    width: 0.3,
    depth: 0.3,
    height: 0.9,
    heightPerLevel: 0.12,
    shape: 'cylinder',
    wall: 'white',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'path',
    props: ['vents'],
  },
  busTerminal: {
    width: 0.84,
    depth: 0.6,
    height: 0.26,
    heightPerLevel: 0.03,
    shape: 'slab',
    wall: 'plaster',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'asphalt',
    props: ['shelter', 'lamps', 'sign'],
  },
  subwayStation: {
    width: 0.5,
    depth: 0.44,
    height: 0.22,
    heightPerLevel: 0.02,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'glass',
    platform: 'path',
    props: ['stairs', 'sign', 'lamps'],
  },
  bikeLane: {
    width: 0.9,
    depth: 0.36,
    height: 0.04,
    wall: 'crop',
    roof: 'none',
    platform: 'asphalt',
    props: [],
  },
  airport: {
    width: 0.9,
    depth: 0.68,
    height: 0.28,
    heightPerLevel: 0.04,
    shape: 'slab',
    wall: 'white',
    roof: 'arch',
    roofColor: 'glass',
    platform: 'asphalt',
    props: ['glassFront', 'dish', 'lamps', 'antenna'],
  },
  playground: {
    width: 0.5,
    depth: 0.42,
    height: 0.06,
    wall: 'parkGrass',
    roof: 'none',
    platform: 'parkGrass',
    props: ['benches', 'trees'],
  },
  swimmingPool: {
    width: 0.82,
    depth: 0.62,
    height: 0.12,
    wall: 'plaster',
    roof: 'none',
    platform: 'path',
    props: ['pond', 'benches', 'lamps'],
  },
  cinema: {
    width: 0.72,
    depth: 0.58,
    height: 0.4,
    heightPerLevel: 0.05,
    wall: 'brickDark',
    roof: 'flat',
    roofColor: 'slate',
    props: ['sign', 'lamps', 'glassFront'],
  },
  stadium: {
    width: 0.9,
    depth: 0.74,
    height: 0.3,
    heightPerLevel: 0.04,
    shape: 'cylinder',
    wall: 'concrete',
    roof: 'none',
    platform: 'parkGrass',
    props: ['lamps', 'stairs'],
  },
  museum: {
    width: 0.78,
    depth: 0.62,
    height: 0.42,
    heightPerLevel: 0.05,
    wall: 'white',
    plinth: 'stone',
    roof: 'flat',
    roofColor: 'slate',
    props: ['columns', 'stairs', 'glassFront'],
  },
  publicLibrary: {
    width: 0.74,
    depth: 0.6,
    height: 0.4,
    heightPerLevel: 0.05,
    wall: 'plaster',
    roof: 'flat',
    roofColor: 'parkGrass',
    props: ['glassFront', 'windows', 'trees'],
  },
  artsCenter: {
    width: 0.76,
    depth: 0.6,
    height: 0.44,
    heightPerLevel: 0.06,
    wall: 'clothRed',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['glassFront', 'sign', 'lamps'],
  },
  university: {
    width: 0.84,
    depth: 0.64,
    height: 0.5,
    heightPerLevel: 0.07,
    wall: 'hallWall',
    plinth: 'stone',
    roof: 'dome',
    roofColor: 'dome',
    props: ['columns', 'stairs', 'clock'],
  },
  spaceCenter: {
    width: 0.6,
    depth: 0.56,
    height: 0.7,
    heightPerLevel: 0.1,
    wall: 'white',
    plinth: 'concrete',
    roof: 'cone',
    roofColor: 'clothRed',
    platform: 'concrete',
    props: ['antenna', 'dish', 'pipes', 'lamps'],
  },
  fireStation: {
    width: 0.72,
    depth: 0.56,
    height: 0.36,
    heightPerLevel: 0.04,
    wall: 'clothRed',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    props: ['door', 'lamps', 'sign'],
  },
  policeStation: {
    width: 0.72,
    depth: 0.56,
    height: 0.38,
    heightPerLevel: 0.04,
    wall: 'slate',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['windows', 'lamps', 'sign'],
  },
  courthouse: {
    width: 0.8,
    depth: 0.62,
    height: 0.48,
    heightPerLevel: 0.06,
    wall: 'plaster',
    plinth: 'stone',
    roof: 'pyramid',
    roofColor: 'slate',
    props: ['columns', 'stairs', 'flagpole'],
  },
};

/** How the original twelve look once the city reaches the Modern era: glass, panels, gardens. */
export const MODERN_SPECS: Partial<Record<BuildingType, ModelSpec>> = {
  townHall: {
    width: 0.86,
    depth: 0.68,
    height: 0.5,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    platform: 'path',
    props: ['glassFront', 'stairs', 'flagpole', 'lamps'],
  },
  house: {
    width: 0.6,
    depth: 0.52,
    height: 0.8,
    heightPerLevel: 0.18,
    wall: 'plaster',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    props: ['balconies', 'windows', 'door'],
  },
  farm: {
    width: 0.8,
    depth: 0.58,
    height: 0.16,
    wall: 'glass',
    roof: 'arch',
    roofColor: 'glass',
    platform: 'soil',
    props: ['crops'],
  },
  shop: {
    width: 0.78,
    depth: 0.62,
    height: 0.55,
    heightPerLevel: 0.1,
    wall: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['glassFront', 'windowBand', 'lamps'],
  },
  workshop: {
    width: 0.72,
    depth: 0.58,
    height: 0.4,
    wall: 'brick',
    roof: 'sawtooth',
    roofColor: 'slate',
    props: ['windowBand', 'vents', 'crates'],
  },
  park: {
    width: 0.5,
    depth: 0.42,
    height: 0.04,
    wall: 'parkGrass',
    roof: 'none',
    platform: 'parkGrass',
    props: ['trees', 'pond', 'benches'],
  },
  well: {
    width: 0.6,
    depth: 0.5,
    height: 0.2,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['tank', 'pipes'],
  },
  inn: {
    width: 0.64,
    depth: 0.54,
    height: 0.9,
    heightPerLevel: 0.15,
    wall: 'glass',
    plinth: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['balconies', 'lamps'],
  },
  powerPlant: {
    width: 0.8,
    depth: 0.64,
    height: 0.18,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'concrete',
    platform: 'path',
    props: ['solar', 'vents'],
  },
  researchCenter: {
    width: 0.74,
    depth: 0.6,
    height: 0.45,
    wall: 'plaster',
    roof: 'dome',
    roofColor: 'dome',
    props: ['glassFront', 'dish', 'antenna'],
  },
  monument: {
    width: 0.42,
    depth: 0.42,
    height: 1.15,
    heightPerLevel: 0.2,
    shape: 'tower',
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['antenna', 'lamps'],
  },
  factory: {
    width: 0.82,
    depth: 0.66,
    height: 0.45,
    wall: 'brick',
    roof: 'sawtooth',
    roofColor: 'roofDark',
    props: ['stack', 'vents', 'pipes', 'crates'],
  },
};
