import type { BuildingType } from '../building/types';
import type { ModelSpec } from './modelSpec';

/**
 * Model specs for buildings without a hand-made model. The twelve original types are modelled
 * by hand for the first three eras (see models.ts); everything else describes itself here.
 */
export const BUILDING_SPECS: Partial<Record<BuildingType, ModelSpec>> = {};

/** How the original twelve look once the city reaches the Modern era: glass, panels, gardens. */
export const MODERN_SPECS: Partial<Record<BuildingType, ModelSpec>> = {
  townHall: {
    width: 0.86,
    depth: 0.68,
    height: 0.5,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    platform: 'path',
    props: ['glassFront', 'stairs', 'flagpole', 'lamps'],
  },
  house: {
    width: 0.6,
    depth: 0.52,
    height: 0.8,
    heightPerLevel: 0.18,
    wall: 'plaster',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'slate',
    props: ['balconies', 'windows', 'door'],
  },
  farm: {
    width: 0.8,
    depth: 0.58,
    height: 0.16,
    wall: 'glass',
    roof: 'arch',
    roofColor: 'glass',
    platform: 'soil',
    props: ['crops'],
  },
  shop: {
    width: 0.78,
    depth: 0.62,
    height: 0.55,
    heightPerLevel: 0.1,
    wall: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['glassFront', 'windowBand', 'lamps'],
  },
  workshop: {
    width: 0.72,
    depth: 0.58,
    height: 0.4,
    wall: 'brick',
    roof: 'sawtooth',
    roofColor: 'slate',
    props: ['windowBand', 'vents', 'crates'],
  },
  park: {
    width: 0.5,
    depth: 0.42,
    height: 0.04,
    wall: 'parkGrass',
    roof: 'none',
    platform: 'parkGrass',
    props: ['trees', 'pond', 'benches'],
  },
  well: {
    width: 0.6,
    depth: 0.5,
    height: 0.2,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    platform: 'concrete',
    props: ['tank', 'pipes'],
  },
  inn: {
    width: 0.64,
    depth: 0.54,
    height: 0.9,
    heightPerLevel: 0.15,
    wall: 'glass',
    plinth: 'plaster',
    roof: 'flat',
    roofColor: 'slate',
    props: ['balconies', 'lamps'],
  },
  powerPlant: {
    width: 0.8,
    depth: 0.64,
    height: 0.18,
    wall: 'concrete',
    roof: 'flat',
    roofColor: 'concrete',
    platform: 'path',
    props: ['solar', 'vents'],
  },
  researchCenter: {
    width: 0.74,
    depth: 0.6,
    height: 0.45,
    wall: 'plaster',
    roof: 'dome',
    roofColor: 'dome',
    props: ['glassFront', 'dish', 'antenna'],
  },
  monument: {
    width: 0.42,
    depth: 0.42,
    height: 1.15,
    heightPerLevel: 0.2,
    shape: 'tower',
    wall: 'glass',
    plinth: 'concrete',
    roof: 'flat',
    roofColor: 'iron',
    props: ['antenna', 'lamps'],
  },
  factory: {
    width: 0.82,
    depth: 0.66,
    height: 0.45,
    wall: 'brick',
    roof: 'sawtooth',
    roofColor: 'roofDark',
    props: ['stack', 'vents', 'pipes', 'crates'],
  },
};
